/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Modelos.Automata;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario A. Yusti
 */
public class JFrame_Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Interfaz
     */
    Automata automata;
    boolean manual;
    int nes;

    public JFrame_Mostrar() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    public void inicio(Automata auto, boolean manual) throws IOException {
        this.automata = auto;
        this.panel1.obtenerAutomata(this.automata);
        this.panel1.pintarMatriz(manual, true);
        this.manual = manual;
        this.nes = this.automata.NombreEstados.length;
        this.jLabel_te0.setText(this.automata.NombreEstados[0]);
        if (this.automata.asociacionColor) {
            this.jLabel_e0.setOpaque(true);
            this.jLabel_e0.setBackground((Color) this.automata.asociaciones.get(this.automata.NombreEstados[0] + ""));
        } else {
            this.jLabel_e0.setIcon(new ImageIcon(ImageIO.read(new File(this.automata.asociaciones.get(this.automata.NombreEstados[0]) + "")).getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        }
        this.jLabel_te1.setText(this.automata.NombreEstados[1]);
        if (this.automata.asociacionColor) {
            this.jLabel_e1.setOpaque(true);
            this.jLabel_e1.setBackground((Color) this.automata.asociaciones.get(this.automata.NombreEstados[1] + ""));
        } else {
            this.jLabel_e1.setIcon(new ImageIcon(ImageIO.read(new File(this.automata.asociaciones.get(this.automata.NombreEstados[1]) + "")).getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        }
        this.jLabel_e2.setVisible(false);
        this.jLabel_e3.setVisible(false);
        this.jLabel_e4.setVisible(false);
        this.jLabel_te2.setVisible(false);
        this.jLabel_te3.setVisible(false);
        this.jLabel_te4.setVisible(false);
        if (this.nes > 2) {
            this.jLabel_e2.setVisible(true);
            this.jLabel_te2.setVisible(true);
            this.jLabel_te2.setText(this.automata.NombreEstados[2]);
            if (this.automata.asociacionColor) {
                this.jLabel_e2.setOpaque(true);
                this.jLabel_e2.setBackground((Color) this.automata.asociaciones.get(this.automata.NombreEstados[2] + ""));
            } else {
                this.jLabel_e2.setIcon(new ImageIcon(ImageIO.read(new File(this.automata.asociaciones.get(this.automata.NombreEstados[2]) + "")).getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
            }
        }
        if (this.nes > 3) {
            this.jLabel_e3.setVisible(true);
            this.jLabel_te3.setVisible(true);
            this.jLabel_te3.setText(this.automata.NombreEstados[3]);
            if (this.automata.asociacionColor) {
                this.jLabel_e3.setOpaque(true);
                this.jLabel_e3.setBackground((Color) this.automata.asociaciones.get(this.automata.NombreEstados[3] + ""));
            } else {
                this.jLabel_e3.setIcon(new ImageIcon(ImageIO.read(new File(this.automata.asociaciones.get(this.automata.NombreEstados[3]) + "")).getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
            }
        }
        if (this.nes > 4) {
            this.jLabel_e4.setVisible(true);
            this.jLabel_te4.setVisible(true);
            this.jLabel_te4.setText(this.automata.NombreEstados[4]);
            if (this.automata.asociacionColor) {
                this.jLabel_e4.setOpaque(true);
                this.jLabel_e4.setBackground((Color) this.automata.asociaciones.get(this.automata.NombreEstados[4] + ""));
            } else {
                this.jLabel_e4.setIcon(new ImageIcon(ImageIO.read(new File(this.automata.asociaciones.get(this.automata.NombreEstados[4]) + "")).getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new Visuales.panel();
        BtnSiguiente = new javax.swing.JButton();
        btn_randomCambiar = new javax.swing.JButton();
        jLabel_e0 = new javax.swing.JLabel();
        jLabel_te0 = new javax.swing.JLabel();
        jLabel_e1 = new javax.swing.JLabel();
        jLabel_te1 = new javax.swing.JLabel();
        jLabel_e2 = new javax.swing.JLabel();
        jLabel_te2 = new javax.swing.JLabel();
        jLabel_e3 = new javax.swing.JLabel();
        jLabel_te3 = new javax.swing.JLabel();
        jLabel_e4 = new javax.swing.JLabel();
        jLabel_te4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(1200, 620));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        btn_randomCambiar.setText("Cambiar Aleatoriamente");
        btn_randomCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_randomCambiarActionPerformed(evt);
            }
        });

        jLabel_te0.setText("Estado 1");

        jLabel_te1.setText("Estado 2");

        jLabel_te2.setText("Estado 3");

        jLabel_te3.setText("Estado 4");

        jLabel_te4.setText("Estado 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_e0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_te0)
                .addGap(18, 18, 18)
                .addComponent(jLabel_e1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_te1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_e2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_te2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_e3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_te3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_e4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_te4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_randomCambiar)
                .addGap(440, 440, 440)
                .addComponent(BtnSiguiente)
                .addContainerGap())
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_randomCambiar)
                        .addComponent(BtnSiguiente))
                    .addComponent(jLabel_e4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_e2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_te2)
                    .addComponent(jLabel_e3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_te3)
                    .addComponent(jLabel_te4)
                    .addComponent(jLabel_te0)
                    .addComponent(jLabel_e0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_e1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_te1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_randomCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_randomCambiarActionPerformed
        if (this.manual) {
            int o = JOptionPane.showConfirmDialog(null, "Desea Cambiar de modo Manual a Aleatorio? \n No podra revertirlo despues");
            this.manual = (o != 0);
            if (!this.manual) {
                btn_randomCambiarActionPerformed(evt);
            }
        } else {
            this.automata.llenarAleatorio();
            this.panel1.limpiar();
            try {
                this.panel1.pintarMatriz(false, true);
            } catch (IOException ex) {
                Logger.getLogger(JFrame_Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_randomCambiarActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        this.setVisible(false);
        JFrame_Principal jframep = new JFrame_Principal();
        try {
            jframep.iniciar(this.automata);
        } catch (IOException ex) {
            Logger.getLogger(JFrame_Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jframep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton btn_randomCambiar;
    private javax.swing.JLabel jLabel_e0;
    private javax.swing.JLabel jLabel_e1;
    private javax.swing.JLabel jLabel_e2;
    private javax.swing.JLabel jLabel_e3;
    private javax.swing.JLabel jLabel_e4;
    private javax.swing.JLabel jLabel_te0;
    private javax.swing.JLabel jLabel_te1;
    private javax.swing.JLabel jLabel_te2;
    private javax.swing.JLabel jLabel_te3;
    private javax.swing.JLabel jLabel_te4;
    private Visuales.panel panel1;
    // End of variables declaration//GEN-END:variables
}
